# Generated by Django 6.0.6 on 2026-06-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('Email', models.CharField()),
                ('Mobile', models.CharField(max_length=10)),
                ('Age', models.CharField()),
                ('Address', models.CharField()),
            ],
        ),
    ]
